# Generated by Django 4.1.7 on 2023-02-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staffmodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='api.jobmodel'),
            preserve_default=False,
        ),
    ]
