# Generated by Django 4.1.7 on 2023-03-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_staffmodel_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='about_service',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='about_service_title',
        ),
        migrations.RemoveField(
            model_name='testimonialmodel',
            name='rate_stars',
        ),
    ]
