# Generated by Django 4.1.7 on 2023-03-30 09:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_blogmodel_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='casestudymodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
