# Generated by Django 4.1.7 on 2023-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_casestudymodel_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='short_description',
            field=models.TextField(default='Tincidunt donec vulputate ipsum erat urna auctor. Eget phasellus ideirs.adipiscing elit. Tincidunt donec vulputate ipsum erat urna auctor. '),
            preserve_default=False,
        ),
    ]
