# Generated by Django 4.1.7 on 2023-03-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogmodel_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
    ]
